version: '3'

services:
  redis:
    image: redis:alpine
    container_name: redis_server
    ports:
      - "6379:6379"
    restart: always

  api:
    build: .
    container_name: flask_app
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    restart: always
